<a href="https://colab.research.google.com/github/marsgitahi/Cancer-Analysis/blob/main/Cancerabyme.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Step 1: Business Understanding

I'm to investigate the impact of various health-related indicators on cancer prevalence and mortality rates in various countries and regions/territories.
I will then identify the variables that will show the correlation with cancer prevalence and mortality rates worldwide, come up with solutions to mitigate their outcome.

In [ ]:
# Load Dataset
#Define the file path
#cp=/content/Cancer.xlsx


# Library (pandas)
import pandas as pd
import xlrd


# Read xlsx file
cp=pd.read_excel("/content/Cancer.xlsx")
cp

,Country or Territory,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Melanoma skin cancer incidence\nAge-standardized rate (world) per 100,000, both sexes, 2018",Breastfeeding at 12 months\nPercent (%) of children who receive any breast milk at 12 months of age,Average births per woman\n2010-2015,...,"Most common cancer cases worldwide, females\n2018","Most common cancer deaths worldwide, females\n2018","Most common cancer cases worldwide, males\n2018","Most common cancer deaths worldwide, males\n2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018","Years lived with disability due to cancer\nBoth sexes, all ages, 2017","Hepatitis B virus vaccination\nHepatitis B vaccination coverage (% of one-year-olds who have received three doses of hepatitis B vaccine), 2017","Radiotherapy availability\nNumber of radiotherapy machines per 1,000 cancer patients","Cervical cancer incidence rates\nAge-standardized rate (world) per 100,000, 2018","HIV prevalence (%)\nBoth sexes, 2017"
0,Afghanistan,0.5,21.4,7,16,3.2,7.6,0.3,88,5.3,...,Breast,Breast,"Lip, oral cavity",Stomach,151,8089.8,65,0,6.6,No data
1,Algeria,1.1,17.5,2.2,12.9,19.9,34.9,0.7,55.1,3,...,Breast,Breast,Lung,Lung,312.6,16404.9,91,0.75,8.1,0.05
2,Azerbaijan,3.2,36.7,0.3,15.4,15.8,23.6,0.53,36.1,2.1,...,Breast,Breast,Lung,Lung,228.1,6685.1,95,0.86,6.5,0.1
3,Albania,4.9,40.9,6.1,13.4,21.6,21.8,1.7,72.3,1.7,...,Breast,Breast,Lung,Lung,401.1,2644.3,99,0.6,6.5,0.05
4,Armenia,5,43.5,1.5,12.2,17.1,23,1.6,52.3,1.7,...,Breast,Breast,Lung,Lung,402.2,3418,94,0.34,8.4,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,Réunion,No data,No data,No data,12.4,No data,No data,3.3,No data,2.4,...,Breast,Breast,Prostate,Lung,590.1,No data,No data,No data,10.5,No data
203,French Polynesia,No data,No data,No data,6.6,No data,No data,6.5,No data,2.1,...,Breast,Lung,Prostate,Lung,661.9,No data,No data,No data,10.1,No data
204,Guadeloupe,No data,No data,No data,10.2,No data,No data,1.5,No data,2,...,Breast,Breast,Prostate,Prostate,776.5,No data,No data,0.88,9.3,No data
205,Guam,No data,No data,No data,8.5,No data,No data,No data,No data,2.4,...,Breast,Lung,Lung,Lung,418,168.8,No data,2.58,18.7,No data
206,Martinique,No data,No data,No data,6.6,No data,No data,2,No data,2,...,Breast,Breast,Prostate,Prostate,747,No data,No data,1.46,7.6,No data

After uploading the file from local storage, i used the pandas and xlrd libraries to read the file.

The output gives the first 5 and last 5 rows, it has 207 rows and 27 columns

In [ ]:
# Information of the dataset
cp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 27 columns):
 #   Column                                                                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                                                                     --------------  -----
 0   Country or Territory                                                                                                                                       207 non-null    object
 1   Cancer deaths attributable to alcohol
Proportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016                       207 non-null    object
 2   Smoking prevalence male
Prevalence (%) of daily smoking for men                                                                                            207 non-null    object
 3   Smoking prevalence female
Prevalence (%) of daily smoking for women                                                                                        207 non-null    object
 4   Cancers attributable to infections
Proportion of cancers attributable to infections (%), by country                                                        207 non-null    object
 5   Obesity prevalence male
International variation in the prevalence of obesity, 2016                                                                         207 non-null    object
 6   Obesity prevalence female
International variation in the prevalence of obesity, 2016                                                                       207 non-null    object
 7   Melanoma skin cancer incidence
Age-standardized rate (world) per 100,000, both sexes, 2018                                                                 207 non-null    object
 8   Breastfeeding at 12 months
Percent (%) of children who receive any breast milk at 12 months of age                                                         207 non-null    object
 9   Average births per woman
2010-2015                                                                                                                         207 non-null    object
 10  Outdoor air pollution
Average annual population-weighted concentrations of PM2.5 (particulate matter of 2.5 μm diameter or less), measured in μg/m3, 2017  207 non-null    object
 11  Indoor air pollution
Proportion (%) of population using solid fuels in 2017                                                                                207 non-null    object
 12  Cancer rank as leading cause of death among 30-69
2016                                                                                                     207 non-null    object
 13  Lung cancer incidence rates, male
Age-standardized rate (world) per 100,000, all ages, 2018                                                                207 non-null    object
 14  Lung cancer incidence rates, female
Age-standardized rate (world) per 100,000, all ages, 2018                                                              207 non-null    object
 15  Breast most frequently diagnosed cancer in women
Countries where breast cancer is the most frequently diagnosed cancer in women, 2018                      207 non-null    object
 16  Human Development Index (HDI) levels
2017                                                                                                                  207 non-null    object
 17  Most common cancer cases worldwide, females
2018                                                                                                           207 non-null    object
 18  Most common cancer deaths worldwide, females
2018                                                                                                          207 non-null    object
 19  Most common cancer cases worldwide, males
2018                                                                                                             207 non-null    object
 20  Most common cancer deaths worldwide, males
2018                                                                                                            207 non-null    object
 21  Cancer survivors
Estimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018                        207 non-null    object
 22  Years lived with disability due to cancer
Both sexes, all ages, 2017                                                                                       207 non-null    object
 23  Hepatitis B virus vaccination
Hepatitis B vaccination coverage (% of one-year-olds who have received three doses of hepatitis B vaccine), 2017             207 non-null    object
 24  Radiotherapy availability
Number of radiotherapy machines per 1,000 cancer patients                                                                        207 non-null    object
 25  Cervical cancer incidence rates
Age-standardized rate (world) per 100,000, 2018                                                                            207 non-null    object
 26  HIV prevalence (%)
Both sexes, 2017                                                                                                                        207 non-null    object
dtypes: object(27)
memory usage: 43.8+ KB

The output gives the column names and shows that all of the columns have object as the datatype.

In [ ]:
# Columns
from tabulate import tabulate

# Get all column names
column_names = cp.columns.tolist()

# Convert column names to a list of lists for tabulate
column_names_table = [[i+1, name] for i, name in enumerate(column_names)]

# Print column names as a table
print(tabulate(column_names_table, headers=["Index", "Column Name"]))

  Index  Column Name
-------  -----------------------------------------------------------------------------------------------------------------------------------
      1  Country or Territory
      2  Cancer deaths attributable to alcohol
         Proportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016
      3  Smoking prevalence male
         Prevalence (%) of daily smoking for men
      4  Smoking prevalence female
         Prevalence (%) of daily smoking for women
      5  Cancers attributable to infections
         Proportion of cancers attributable to infections (%), by country
      6  Obesity prevalence male
         International variation in the prevalence of obesity, 2016
      7  Obesity prevalence female
         International variation in the prevalence of obesity, 2016
      8  Melanoma skin cancer incidence
         Age-standardized rate (world) per 100,000, both sexes, 2018
      9  Breastfeeding at 12 months
         Percent (%) of children who receive any breast milk at 12 months of age
     10  Average births per woman
         2010-2015
     11  Outdoor air pollution
         Average annual population-weighted concentrations of PM2.5 (particulate matter of 2.5 μm diameter or less), measured in μg/m3, 2017
     12  Indoor air pollution
         Proportion (%) of population using solid fuels in 2017
     13  Cancer rank as leading cause of death among 30-69
         2016
     14  Lung cancer incidence rates, male
         Age-standardized rate (world) per 100,000, all ages, 2018
     15  Lung cancer incidence rates, female
         Age-standardized rate (world) per 100,000, all ages, 2018
     16  Breast most frequently diagnosed cancer in women
         Countries where breast cancer is the most frequently diagnosed cancer in women, 2018
     17  Human Development Index (HDI) levels
         2017
     18  Most common cancer cases worldwide, females
         2018
     19  Most common cancer deaths worldwide, females
         2018
     20  Most common cancer cases worldwide, males
         2018
     21  Most common cancer deaths worldwide, males
         2018
     22  Cancer survivors
         Estimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018
     23  Years lived with disability due to cancer
         Both sexes, all ages, 2017
     24  Hepatitis B virus vaccination
         Hepatitis B vaccination coverage (% of one-year-olds who have received three doses of hepatitis B vaccine), 2017
     25  Radiotherapy availability
         Number of radiotherapy machines per 1,000 cancer patients
     26  Cervical cancer incidence rates
         Age-standardized rate (world) per 100,000, 2018
     27  HIV prevalence (%)
         Both sexes, 2017

I wanted a list of the variables which are represented as the columns of the dataset.

**Step 2: Data Understanding**

Here i will select the health indicators that have high impact on cancer prevalence and mortality rate.

Then check for missing values,duplicates and outliers.

In [ ]:
# Select Column names that will help anaswer your problem
selected_columns = [
    'Country or Territory',
    'Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016',
    'Smoking prevalence male\nPrevalence (%) of daily smoking for men',
    'Smoking prevalence female\nPrevalence (%) of daily smoking for women',
    'Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country',
    'Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016',
    'Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016',
    'Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018',
    'Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018',
    'Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018'
]

# Select the relevant columns from the DataFrame
selected_cp = cp[selected_columns]
selected_cp

,Country or Territory,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
0,Afghanistan,0.5,21.4,7,16,3.2,7.6,9.4,3.2,151
1,Algeria,1.1,17.5,2.2,12.9,19.9,34.9,17.4,2.9,312.6
2,Azerbaijan,3.2,36.7,0.3,15.4,15.8,23.6,25.5,2.6,228.1
3,Albania,4.9,40.9,6.1,13.4,21.6,21.8,37.8,7.1,401.1
4,Armenia,5,43.5,1.5,12.2,17.1,23,58.5,8.5,402.2
...,...,...,...,...,...,...,...,...,...,...
202,Réunion,No data,No data,No data,12.4,No data,No data,34.6,9.6,590.1
203,French Polynesia,No data,No data,No data,6.6,No data,No data,55.7,23.4,661.9
204,Guadeloupe,No data,No data,No data,10.2,No data,No data,13,6.5,776.5
205,Guam,No data,No data,No data,8.5,No data,No data,53.7,24.3,418
206,Martinique,No data,No data,No data,6.6,No data,No data,12.3,9.2,747

From the 27 columns i now have 10 columns.

The output shows the first and last 5 rows

In [ ]:
# Shape of the selected dataframe
print("Shape of selected_cp:", selected_cp.shape)

Shape of selected_cp: (207, 10)

The output shows that the dataframe has 207 rows and 10 columns

In [ ]:
# The first few rows of the selected_cp
print("\nFirst few rows of selected_cp:")
selected_cp.head()

First few rows of selected_cp:

,Country or Territory,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
0,Afghanistan,0.5,21.4,7,16,3.2,7.6,9.4,3.2,151
1,Algeria,1.1,17.5,2.2,12.9,19.9,34.9,17.4,2.9,312.6
2,Azerbaijan,3.2,36.7,0.3,15.4,15.8,23.6,25.5,2.6,228.1
3,Albania,4.9,40.9,6.1,13.4,21.6,21.8,37.8,7.1,401.1
4,Armenia,5,43.5,1.5,12.2,17.1,23,58.5,8.5,402.2

The output gives the first few rows of the selected_cp dataframe

In [ ]:
# The last few rows of selected_cp
print("\nLast few rows of selected_cp:")
selected_cp.tail()

Last few rows of selected_cp:

,Country or Territory,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
202,Réunion,No data,No data,No data,12.4,No data,No data,34.6,9.6,590.1
203,French Polynesia,No data,No data,No data,6.6,No data,No data,55.7,23.4,661.9
204,Guadeloupe,No data,No data,No data,10.2,No data,No data,13,6.5,776.5
205,Guam,No data,No data,No data,8.5,No data,No data,53.7,24.3,418
206,Martinique,No data,No data,No data,6.6,No data,No data,12.3,9.2,747

The output shows the last few rows of the selected_cp dataframe

In [ ]:
# Check for missing values
print("\nMissing values in selected_cp:")
print(selected_cp.isnull().sum())

Missing values in selected_cp:
Country or Territory                                                                                                                     0
Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016    0
Smoking prevalence male\nPrevalence (%) of daily smoking for men                                                                         0
Smoking prevalence female\nPrevalence (%) of daily smoking for women                                                                     0
Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country                                     0
Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016                                                      0
Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016                                                    0
Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018                                             0
Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018                                           0
Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018     0
dtype: int64

Selected_cp dataframe has no missing values

In [ ]:
# Display data types of columns
print("\nData types of columns in selected_cp:")
print(selected_cp.dtypes)

Data types of columns in selected_cp:
Country or Territory                                                                                                                     object
Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016    object
Smoking prevalence male\nPrevalence (%) of daily smoking for men                                                                         object
Smoking prevalence female\nPrevalence (%) of daily smoking for women                                                                     object
Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country                                     object
Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016                                                      object
Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016                                                    object
Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018                                             object
Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018                                           object
Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018     object
dtype: object

All the columns have object as the data type. This means that there is mixed data types like string and numeric data.

For further analysis, there is need to convert the columns to numeric data type.

In [ ]:
import pandas as pd # Import the pandas library

#Convert selected numeric columns to numeric data type
selected_cp = selected_cp.copy()

# Define the list of numeric columns
numeric_columns = [
    'Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016',
    'Smoking prevalence male\nPrevalence (%) of daily smoking for men',
    'Smoking prevalence female\nPrevalence (%) of daily smoking for women',
    'Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country',
    'Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016',
    'Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016',
    'Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018',
    'Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018',
    'Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018']

selected_cp[numeric_columns] = selected_cp[numeric_columns].apply(pd.to_numeric, errors='coerce')
selected_cp[numeric_columns]

,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
0,0.5,21.4,7.0,16.0,3.2,7.6,9.4,3.2,151.0
1,1.1,17.5,2.2,12.9,19.9,34.9,17.4,2.9,312.6
2,3.2,36.7,0.3,15.4,15.8,23.6,25.5,2.6,228.1
3,4.9,40.9,6.1,13.4,21.6,21.8,37.8,7.1,401.1
4,5.0,43.5,1.5,12.2,17.1,23.0,58.5,8.5,402.2
...,...,...,...,...,...,...,...,...,...
202,NaN,NaN,NaN,12.4,NaN,NaN,34.6,9.6,590.1
203,NaN,NaN,NaN,6.6,NaN,NaN,55.7,23.4,661.9
204,NaN,NaN,NaN,10.2,NaN,NaN,13.0,6.5,776.5
205,NaN,NaN,NaN,8.5,NaN,NaN,53.7,24.3,418.0
206,NaN,NaN,NaN,6.6,NaN,NaN,12.3,9.2,747.0



Cancer deaths attributable to alcohol: Proportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older in 2016.

Smoking prevalence male: Prevalence (%) of daily smoking for men.

Smoking prevalence female: Prevalence (%) of daily smoking for women.

Cancers attributable to infections: Proportion of cancers attributable to infections (%), by country.

Obesity prevalence male: International variation in the prevalence of obesity in males in 2016.

Obesity prevalence female: International variation in the prevalence of obesity in females in 2016.

Lung cancer incidence rates, male: Age-standardized rate (world) per 100,000 for lung cancer in males in 2018.

Lung cancer incidence rates, female: Age-standardized rate (world) per 100,000 for lung cancer in females in 2018.

Cancer survivors: Estimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, in 2018.

The NaN values represent missing data points where information wasn't available for certain countries or territories.

In [ ]:
newnumericc=selected_cp[numeric_columns]
newnumericc

,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
0,0.5,21.4,7.0,16.0,3.2,7.6,9.4,3.2,151.0
1,1.1,17.5,2.2,12.9,19.9,34.9,17.4,2.9,312.6
2,3.2,36.7,0.3,15.4,15.8,23.6,25.5,2.6,228.1
3,4.9,40.9,6.1,13.4,21.6,21.8,37.8,7.1,401.1
4,5.0,43.5,1.5,12.2,17.1,23.0,58.5,8.5,402.2
...,...,...,...,...,...,...,...,...,...
202,NaN,NaN,NaN,12.4,NaN,NaN,34.6,9.6,590.1
203,NaN,NaN,NaN,6.6,NaN,NaN,55.7,23.4,661.9
204,NaN,NaN,NaN,10.2,NaN,NaN,13.0,6.5,776.5
205,NaN,NaN,NaN,8.5,NaN,NaN,53.7,24.3,418.0
206,NaN,NaN,NaN,6.6,NaN,NaN,12.3,9.2,747.0

In [ ]:
#Summary Statistics
print("\nDescriptive statistics for the numeric columns:")
newnumericc.describe()

Descriptive statistics for the numeric columns:

,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
count,184.000000,189.000000,191.000000,184.000000,191.00000,191.000000,185.000000,184.000000,185.000000
mean,5.291304,23.939683,7.112565,19.080978,16.34555,23.334031,22.545189,9.440543,435.127027
std,2.948025,11.825503,7.254766,12.113494,11.45113,12.360542,18.471358,8.777530,310.020328
min,0.200000,1.300000,0.100000,3.600000,1.60000,2.600000,0.380000,0.040000,74.800000
25%,2.900000,14.300000,1.500000,9.600000,5.30000,13.400000,6.400000,2.600000,202.300000
50%,5.150000,21.600000,3.900000,16.900000,17.10000,22.800000,16.900000,6.400000,314.200000
75%,7.400000,33.500000,12.400000,25.575000,23.40000,29.150000,35.500000,13.225000,591.800000
max,14.500000,66.600000,42.100000,54.800000,58.70000,63.300000,77.400000,41.400000,1849.800000

**DATA CLEANING**

In [ ]:
# Duplicates
newnumericc.duplicated().sum()

7

In [ ]:
#Removing Duplicates
newnumericc.drop_duplicates(inplace=True)

<ipython-input-16-b84800ff4ddf>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newnumericc.drop_duplicates(inplace=True)

In [ ]:
#Checking if there are still duplicates
duplicates=newnumericc.duplicated().sum()
print(duplicates)

0

There are no duplicates

In [ ]:
# Outliers
outliers = newnumericc.apply(lambda x: (x - x.mean()).abs() > 3 * x.std()).sum()

print("\nOutliers:")
print(outliers)

Outliers:
Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016    1
Smoking prevalence male\nPrevalence (%) of daily smoking for men                                                                         1
Smoking prevalence female\nPrevalence (%) of daily smoking for women                                                                     1
Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country                                     1
Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016                                                      3
Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016                                                    1
Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018                                             0
Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018                                           2
Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018     2
dtype: int64

It is only Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018 column that has no outlier

In [ ]:
# Define the z-score threshold for outlier detection
threshold = 3

# Calculate z-scores for each numerical column
z_scores = newnumericc.apply(lambda x: (x - x.mean()) / x.std())

# Find rows where any z-score exceeds the threshold
outlier_rows = z_scores[(z_scores.abs() > threshold).any(axis=1)]
outlier_rows

,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
7,0.604949,-0.688461,0.847225,-1.282091,1.150331,0.409693,0.349504,1.596086,4.535003
59,2.065345,0.672174,1.876775,-0.938437,1.028025,0.101863,2.945074,3.612552,1.752112
82,3.118188,1.254081,-0.443145,-0.443911,-0.020307,-0.181664,1.496509,0.089401,0.342667
101,0.435135,-0.688461,0.792315,-1.282091,1.194011,0.652716,0.080254,1.913283,4.011082
140,0.333247,-1.210465,-0.868692,3.001007,-0.963806,0.231475,-0.991361,-0.873518,-0.651177
148,-1.229037,3.675839,-0.690237,-0.033203,-1.016222,-1.169959,-0.178226,-0.397723,-0.452859
151,0.740800,-0.654231,1.396318,-1.265327,0.512595,-0.513796,0.785689,3.034800,2.025001
170,NaN,1.023029,4.800697,NaN,3.692536,3.236864,NaN,NaN,NaN
179,NaN,NaN,-0.182325,NaN,3.089745,2.872329,NaN,NaN,NaN
185,NaN,NaN,1.272772,NaN,3.159634,2.904732,NaN,NaN,NaN

In [ ]:
# Removing Outliers
newnumericc_filtered = newnumericc.drop(outlier_rows.index)

# Display the filtered DataFrame
newnumericc_filtered

,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
0,0.5,21.4,7.0,16.0,3.2,7.6,9.4,3.2,151.0
1,1.1,17.5,2.2,12.9,19.9,34.9,17.4,2.9,312.6
2,3.2,36.7,0.3,15.4,15.8,23.6,25.5,2.6,228.1
3,4.9,40.9,6.1,13.4,21.6,21.8,37.8,7.1,401.1
4,5.0,43.5,1.5,12.2,17.1,23.0,58.5,8.5,402.2
...,...,...,...,...,...,...,...,...,...
202,NaN,NaN,NaN,12.4,NaN,NaN,34.6,9.6,590.1
203,NaN,NaN,NaN,6.6,NaN,NaN,55.7,23.4,661.9
204,NaN,NaN,NaN,10.2,NaN,NaN,13.0,6.5,776.5
205,NaN,NaN,NaN,8.5,NaN,NaN,53.7,24.3,418.0
206,NaN,NaN,NaN,6.6,NaN,NaN,12.3,9.2,747.0

In [ ]:
 #Missing Values Check
missing_values =newnumericc.isnull().sum()
print(missing_values)

Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016    23
Smoking prevalence male\nPrevalence (%) of daily smoking for men                                                                         18
Smoking prevalence female\nPrevalence (%) of daily smoking for women                                                                     16
Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country                                     23
Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016                                                      16
Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016                                                    16
Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018                                             22
Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018                                           23
Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018     22
dtype: int64

The selected columns have missing values and there is a need to remove them by imputation to enable further analysis.

In [ ]:
# Removing missing values
clean_cp=newnumericc.dropna()
clean_cp

,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
0,0.5,21.4,7.0,16.0,3.2,7.6,9.4,3.2,151.0
1,1.1,17.5,2.2,12.9,19.9,34.9,17.4,2.9,312.6
2,3.2,36.7,0.3,15.4,15.8,23.6,25.5,2.6,228.1
3,4.9,40.9,6.1,13.4,21.6,21.8,37.8,7.1,401.1
4,5.0,43.5,1.5,12.2,17.1,23.0,58.5,8.5,402.2
...,...,...,...,...,...,...,...,...,...
189,4.8,37.5,14.5,5.4,21.9,21.6,41.0,8.4,743.2
190,1.5,37.4,21.3,7.3,27.4,37.0,31.3,14.8,593.7
191,6.7,19.0,16.1,5.4,24.5,20.7,40.0,18.2,975.6
192,6.2,23.5,13.7,5.7,29.2,28.5,28.2,11.8,729.5
193,4.4,22.3,5.1,11.0,10.8,26.0,21.8,5.1,432.1

In [ ]:
#Completeness
completeness=clean_cp.notnull().sum()/len(clean_cp)*100
print(completeness)

Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016    100.0
Smoking prevalence male\nPrevalence (%) of daily smoking for men                                                                         100.0
Smoking prevalence female\nPrevalence (%) of daily smoking for women                                                                     100.0
Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country                                     100.0
Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016                                                      100.0
Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016                                                    100.0
Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018                                             100.0
Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018                                           100.0
Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018     100.0
dtype: float64

Ths shows that there is consistency in the completeness

In [ ]:
# Check datatypes
clean_cp.dtypes

Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016    float64
Smoking prevalence male\nPrevalence (%) of daily smoking for men                                                                         float64
Smoking prevalence female\nPrevalence (%) of daily smoking for women                                                                     float64
Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country                                     float64
Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016                                                      float64
Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016                                                    float64
Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018                                             float64
Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018                                           float64
Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018     float64
dtype: object

The columns have float as the datatype

In [ ]:
# Convert data types
numeric_columns = clean_cp.columns[1:]
clean_cp[numeric_columns] = clean_cp[numeric_columns].astype(float)
clean_cp[numeric_columns]

<ipython-input-21-32ac8b97fb7f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_cp[numeric_columns] = clean_cp[numeric_columns].astype(float)

,Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
0,21.4,7.0,16.0,3.2,7.6,9.4,3.2,151.0
1,17.5,2.2,12.9,19.9,34.9,17.4,2.9,312.6
2,36.7,0.3,15.4,15.8,23.6,25.5,2.6,228.1
3,40.9,6.1,13.4,21.6,21.8,37.8,7.1,401.1
4,43.5,1.5,12.2,17.1,23.0,58.5,8.5,402.2
...,...,...,...,...,...,...,...,...
189,37.5,14.5,5.4,21.9,21.6,41.0,8.4,743.2
190,37.4,21.3,7.3,27.4,37.0,31.3,14.8,593.7
191,19.0,16.1,5.4,24.5,20.7,40.0,18.2,975.6
192,23.5,13.7,5.7,29.2,28.5,28.2,11.8,729.5
193,22.3,5.1,11.0,10.8,26.0,21.8,5.1,432.1

**Exploratory Data Analysis**

In [ ]:
#Summary Statistics
clean_cp.describe()

,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
count,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000
mean,5.323256,24.373256,6.963372,19.327907,14.900581,21.494186,22.382442,9.344535,431.886047
std,2.966841,11.585219,6.812596,12.220328,9.396176,10.282710,18.350227,8.786039,313.435446
min,0.200000,4.400000,0.100000,3.600000,1.600000,2.600000,0.850000,0.040000,74.800000
25%,2.875000,14.850000,1.475000,9.700000,4.775000,12.700000,6.400000,2.600000,206.050000
50%,5.300000,22.050000,3.800000,17.150000,16.550000,21.800000,16.650000,6.050000,308.500000
75%,7.400000,33.500000,12.450000,26.025000,22.625000,27.950000,35.550000,13.225000,575.925000
max,14.500000,66.600000,28.100000,54.800000,39.900000,55.000000,77.400000,41.400000,1849.800000