<a href="https://colab.research.google.com/github/marsgitahi/Cancer-Analysis/blob/main/Cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Step 1: Business Understanding

I'm to investigate the impact of various health-related indicators on cancer prevalence and mortality rates in various countries and regions/territories.
I will then identify the variables that will show the correlation with cancer prevalence and mortality rates worldwide, come up with solutions to mitigate their outcome.

In [ ]:
# Load Dataset
#Define the file path
#cp=/content/Cancer.xlsx


# Library (pandas)
import pandas as pd
import xlrd


# Read xlsx file
cp=pd.read_excel("/content/Cancer.xlsx")
cp

,Country or Territory,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Melanoma skin cancer incidence\nAge-standardized rate (world) per 100,000, both sexes, 2018",Breastfeeding at 12 months\nPercent (%) of children who receive any breast milk at 12 months of age,Average births per woman\n2010-2015,...,"Most common cancer cases worldwide, females\n2018","Most common cancer deaths worldwide, females\n2018","Most common cancer cases worldwide, males\n2018","Most common cancer deaths worldwide, males\n2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018","Years lived with disability due to cancer\nBoth sexes, all ages, 2017","Hepatitis B virus vaccination\nHepatitis B vaccination coverage (% of one-year-olds who have received three doses of hepatitis B vaccine), 2017","Radiotherapy availability\nNumber of radiotherapy machines per 1,000 cancer patients","Cervical cancer incidence rates\nAge-standardized rate (world) per 100,000, 2018","HIV prevalence (%)\nBoth sexes, 2017"
0,Afghanistan,0.5,21.4,7,16,3.2,7.6,0.3,88,5.3,...,Breast,Breast,"Lip, oral cavity",Stomach,151,8089.8,65,0,6.6,No data
1,Algeria,1.1,17.5,2.2,12.9,19.9,34.9,0.7,55.1,3,...,Breast,Breast,Lung,Lung,312.6,16404.9,91,0.75,8.1,0.05
2,Azerbaijan,3.2,36.7,0.3,15.4,15.8,23.6,0.53,36.1,2.1,...,Breast,Breast,Lung,Lung,228.1,6685.1,95,0.86,6.5,0.1
3,Albania,4.9,40.9,6.1,13.4,21.6,21.8,1.7,72.3,1.7,...,Breast,Breast,Lung,Lung,401.1,2644.3,99,0.6,6.5,0.05
4,Armenia,5,43.5,1.5,12.2,17.1,23,1.6,52.3,1.7,...,Breast,Breast,Lung,Lung,402.2,3418,94,0.34,8.4,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,Réunion,No data,No data,No data,12.4,No data,No data,3.3,No data,2.4,...,Breast,Breast,Prostate,Lung,590.1,No data,No data,No data,10.5,No data
203,French Polynesia,No data,No data,No data,6.6,No data,No data,6.5,No data,2.1,...,Breast,Lung,Prostate,Lung,661.9,No data,No data,No data,10.1,No data
204,Guadeloupe,No data,No data,No data,10.2,No data,No data,1.5,No data,2,...,Breast,Breast,Prostate,Prostate,776.5,No data,No data,0.88,9.3,No data
205,Guam,No data,No data,No data,8.5,No data,No data,No data,No data,2.4,...,Breast,Lung,Lung,Lung,418,168.8,No data,2.58,18.7,No data
206,Martinique,No data,No data,No data,6.6,No data,No data,2,No data,2,...,Breast,Breast,Prostate,Prostate,747,No data,No data,1.46,7.6,No data

The output gives the first 5 and last 5 rows, it has 207 rows and 27 columns

In [ ]:
# Information of the dataset
cp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 27 columns):
 #   Column                                                                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                                                                     --------------  -----
 0   Country or Territory                                                                                                                                       207 non-null    object
 1   Cancer deaths attributable to alcohol
Proportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016                       207 non-null    object
 2   Smoking prevalence male
Prevalence (%) of daily smoking for men                                                                                            207 non-null    object
 3   Smoking prevalence female
Prevalence (%) of daily smoking for women                                                                                        207 non-null    object
 4   Cancers attributable to infections
Proportion of cancers attributable to infections (%), by country                                                        207 non-null    object
 5   Obesity prevalence male
International variation in the prevalence of obesity, 2016                                                                         207 non-null    object
 6   Obesity prevalence female
International variation in the prevalence of obesity, 2016                                                                       207 non-null    object
 7   Melanoma skin cancer incidence
Age-standardized rate (world) per 100,000, both sexes, 2018                                                                 207 non-null    object
 8   Breastfeeding at 12 months
Percent (%) of children who receive any breast milk at 12 months of age                                                         207 non-null    object
 9   Average births per woman
2010-2015                                                                                                                         207 non-null    object
 10  Outdoor air pollution
Average annual population-weighted concentrations of PM2.5 (particulate matter of 2.5 μm diameter or less), measured in μg/m3, 2017  207 non-null    object
 11  Indoor air pollution
Proportion (%) of population using solid fuels in 2017                                                                                207 non-null    object
 12  Cancer rank as leading cause of death among 30-69
2016                                                                                                     207 non-null    object
 13  Lung cancer incidence rates, male
Age-standardized rate (world) per 100,000, all ages, 2018                                                                207 non-null    object
 14  Lung cancer incidence rates, female
Age-standardized rate (world) per 100,000, all ages, 2018                                                              207 non-null    object
 15  Breast most frequently diagnosed cancer in women
Countries where breast cancer is the most frequently diagnosed cancer in women, 2018                      207 non-null    object
 16  Human Development Index (HDI) levels
2017                                                                                                                  207 non-null    object
 17  Most common cancer cases worldwide, females
2018                                                                                                           207 non-null    object
 18  Most common cancer deaths worldwide, females
2018                                                                                                          207 non-null    object
 19  Most common cancer cases worldwide, males
2018                                                                                                             207 non-null    object
 20  Most common cancer deaths worldwide, males
2018                                                                                                            207 non-null    object
 21  Cancer survivors
Estimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018                        207 non-null    object
 22  Years lived with disability due to cancer
Both sexes, all ages, 2017                                                                                       207 non-null    object
 23  Hepatitis B virus vaccination
Hepatitis B vaccination coverage (% of one-year-olds who have received three doses of hepatitis B vaccine), 2017             207 non-null    object
 24  Radiotherapy availability
Number of radiotherapy machines per 1,000 cancer patients                                                                        207 non-null    object
 25  Cervical cancer incidence rates
Age-standardized rate (world) per 100,000, 2018                                                                            207 non-null    object
 26  HIV prevalence (%)
Both sexes, 2017                                                                                                                        207 non-null    object
dtypes: object(27)
memory usage: 43.8+ KB

The output gives the column names and shows that all of the columns have object as the datatype.

In [ ]:
# Columns
from tabulate import tabulate

# Get all column names
column_names = cp.columns.tolist()

# Convert column names to a list of lists for tabulate
column_names_table = [[i+1, name] for i, name in enumerate(column_names)]

# Print column names as a table
print(tabulate(column_names_table, headers=["Index", "Column Name"]))

  Index  Column Name
-------  -----------------------------------------------------------------------------------------------------------------------------------
      1  Country or Territory
      2  Cancer deaths attributable to alcohol
         Proportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016
      3  Smoking prevalence male
         Prevalence (%) of daily smoking for men
      4  Smoking prevalence female
         Prevalence (%) of daily smoking for women
      5  Cancers attributable to infections
         Proportion of cancers attributable to infections (%), by country
      6  Obesity prevalence male
         International variation in the prevalence of obesity, 2016
      7  Obesity prevalence female
         International variation in the prevalence of obesity, 2016
      8  Melanoma skin cancer incidence
         Age-standardized rate (world) per 100,000, both sexes, 2018
      9  Breastfeeding at 12 months
         Percent (%) of children who receive any breast milk at 12 months of age
     10  Average births per woman
         2010-2015
     11  Outdoor air pollution
         Average annual population-weighted concentrations of PM2.5 (particulate matter of 2.5 μm diameter or less), measured in μg/m3, 2017
     12  Indoor air pollution
         Proportion (%) of population using solid fuels in 2017
     13  Cancer rank as leading cause of death among 30-69
         2016
     14  Lung cancer incidence rates, male
         Age-standardized rate (world) per 100,000, all ages, 2018
     15  Lung cancer incidence rates, female
         Age-standardized rate (world) per 100,000, all ages, 2018
     16  Breast most frequently diagnosed cancer in women
         Countries where breast cancer is the most frequently diagnosed cancer in women, 2018
     17  Human Development Index (HDI) levels
         2017
     18  Most common cancer cases worldwide, females
         2018
     19  Most common cancer deaths worldwide, females
         2018
     20  Most common cancer cases worldwide, males
         2018
     21  Most common cancer deaths worldwide, males
         2018
     22  Cancer survivors
         Estimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018
     23  Years lived with disability due to cancer
         Both sexes, all ages, 2017
     24  Hepatitis B virus vaccination
         Hepatitis B vaccination coverage (% of one-year-olds who have received three doses of hepatitis B vaccine), 2017
     25  Radiotherapy availability
         Number of radiotherapy machines per 1,000 cancer patients
     26  Cervical cancer incidence rates
         Age-standardized rate (world) per 100,000, 2018
     27  HIV prevalence (%)
         Both sexes, 2017

I wanted a list of the variables which are represented as the columns of the dataset.

Step 2: Data Understanding

Here i will select the health indicators that have high impact on cancer prevalence and mortality rate.

Then check for missing values,duplicates and outliers.

In [ ]:
# Select Column names that will help anaswer your problem
selected_columns = [
    'Country or Territory',
    'Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016',
    'Smoking prevalence male\nPrevalence (%) of daily smoking for men',
    'Smoking prevalence female\nPrevalence (%) of daily smoking for women',
    'Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country',
    'Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016',
    'Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016',
    'Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018',
    'Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018',
    'Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018'
]

# Select the relevant columns from the DataFrame
selected_cp = cp[selected_columns]
selected_cp

,Country or Territory,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
0,Afghanistan,0.5,21.4,7,16,3.2,7.6,9.4,3.2,151
1,Algeria,1.1,17.5,2.2,12.9,19.9,34.9,17.4,2.9,312.6
2,Azerbaijan,3.2,36.7,0.3,15.4,15.8,23.6,25.5,2.6,228.1
3,Albania,4.9,40.9,6.1,13.4,21.6,21.8,37.8,7.1,401.1
4,Armenia,5,43.5,1.5,12.2,17.1,23,58.5,8.5,402.2
...,...,...,...,...,...,...,...,...,...,...
202,Réunion,No data,No data,No data,12.4,No data,No data,34.6,9.6,590.1
203,French Polynesia,No data,No data,No data,6.6,No data,No data,55.7,23.4,661.9
204,Guadeloupe,No data,No data,No data,10.2,No data,No data,13,6.5,776.5
205,Guam,No data,No data,No data,8.5,No data,No data,53.7,24.3,418
206,Martinique,No data,No data,No data,6.6,No data,No data,12.3,9.2,747

From the 27 columns i now have 10 columns.

The output shows the first and last 5 rows

In [ ]:
# Shape of the selected dataframe
print("Shape of selected_cp:", selected_cp.shape)

Shape of selected_cp: (207, 10)

The output shows that the dataframe has 207 rows and 10 columns

In [ ]:
# The first few rows of the selected_cp
print("\nFirst few rows of selected_cp:")
selected_cp.head()

First few rows of selected_cp:

,Country or Territory,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
0,Afghanistan,0.5,21.4,7,16,3.2,7.6,9.4,3.2,151
1,Algeria,1.1,17.5,2.2,12.9,19.9,34.9,17.4,2.9,312.6
2,Azerbaijan,3.2,36.7,0.3,15.4,15.8,23.6,25.5,2.6,228.1
3,Albania,4.9,40.9,6.1,13.4,21.6,21.8,37.8,7.1,401.1
4,Armenia,5,43.5,1.5,12.2,17.1,23,58.5,8.5,402.2

The output gives the first few rows of the selected_cp dataframe

In [ ]:
# The last few rows of selected_cp
print("\nLast few rows of selected_cp:")
selected_cp.tail()

Last few rows of selected_cp:

,Country or Territory,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
202,Réunion,No data,No data,No data,12.4,No data,No data,34.6,9.6,590.1
203,French Polynesia,No data,No data,No data,6.6,No data,No data,55.7,23.4,661.9
204,Guadeloupe,No data,No data,No data,10.2,No data,No data,13,6.5,776.5
205,Guam,No data,No data,No data,8.5,No data,No data,53.7,24.3,418
206,Martinique,No data,No data,No data,6.6,No data,No data,12.3,9.2,747

The output shows the last few rows of the selected_cp dataframe

In [ ]:
# Check for missing values
print("\nMissing values in selected_cp:")
print(selected_cp.isnull().sum())

Missing values in selected_cp:
Country or Territory                                                                                                                     0
Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016    0
Smoking prevalence male\nPrevalence (%) of daily smoking for men                                                                         0
Smoking prevalence female\nPrevalence (%) of daily smoking for women                                                                     0
Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country                                     0
Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016                                                      0
Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016                                                    0
Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018                                             0
Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018                                           0
Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018     0
dtype: int64

Selected_cp dataframe has no missing values

In [ ]:
# Display data types of columns
print("\nData types of columns in selected_cp:")
print(selected_cp.dtypes)

Data types of columns in selected_cp:
Country or Territory                                                                                                                     object
Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016    object
Smoking prevalence male\nPrevalence (%) of daily smoking for men                                                                         object
Smoking prevalence female\nPrevalence (%) of daily smoking for women                                                                     object
Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country                                     object
Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016                                                      object
Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016                                                    object
Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018                                             object
Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018                                           object
Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018     object
dtype: object

All the columns have object as the data type. This means that there is mixed data types like string and numeric data.

For further analysis, there is need to convert the columns to numeric data type.

In [ ]:
columns_to_convert = ['Country or Territory',
'Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016',
'Smoking prevalence male\nPrevalence (%) of daily smoking for men',
'Smoking prevalence female\nPrevalence (%) of daily smoking for women',
'Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country',
'Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016',
'Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016',
'Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018',
'Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018',
'Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018']

# Create a new DataFrame with the specified columns converted to numeric
numeric_columns = selected_cp[columns_to_convert].apply(pd.to_numeric, errors='coerce')

# Print the new DataFrame
numeric_columns

,Country or Territory,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
0,NaN,0.5,21.4,7.0,16.0,3.2,7.6,9.4,3.2,151.0
1,NaN,1.1,17.5,2.2,12.9,19.9,34.9,17.4,2.9,312.6
2,NaN,3.2,36.7,0.3,15.4,15.8,23.6,25.5,2.6,228.1
3,NaN,4.9,40.9,6.1,13.4,21.6,21.8,37.8,7.1,401.1
4,NaN,5.0,43.5,1.5,12.2,17.1,23.0,58.5,8.5,402.2
...,...,...,...,...,...,...,...,...,...,...
202,NaN,NaN,NaN,NaN,12.4,NaN,NaN,34.6,9.6,590.1
203,NaN,NaN,NaN,NaN,6.6,NaN,NaN,55.7,23.4,661.9
204,NaN,NaN,NaN,NaN,10.2,NaN,NaN,13.0,6.5,776.5
205,NaN,NaN,NaN,NaN,8.5,NaN,NaN,53.7,24.3,418.0
206,NaN,NaN,NaN,NaN,6.6,NaN,NaN,12.3,9.2,747.0

Now we can do futrher analysis

In [ ]:
 #Missing Values Check
missing_values = numeric_columns.isnull().sum()
print(missing_values)

Country or Territory                                                                                                                     207
Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016     23
Smoking prevalence male\nPrevalence (%) of daily smoking for men                                                                          18
Smoking prevalence female\nPrevalence (%) of daily smoking for women                                                                      16
Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country                                      23
Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016                                                       16
Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016                                                     16
Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018                                              22
Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018                                            23
Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018      22
dtype: int64

In [ ]:
# Convert all columns to numeric except for 'Country'
for col in selected_cp.columns:
    if col != 'Country or Territory':
        selected_cp[col] = pd.to_numeric(selected_cp[col], errors='ignore')

# Print the dataframe
selected_cp

<ipython-input-13-1b1170f41ecd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_cp[col] = pd.to_numeric(selected_cp[col], errors='ignore')

,Country or Territory,"Cancer deaths attributable to alcohol\nProportion (%) of cancer deaths caused by alcohol drinking in men ages 15 years or older, 2016",Smoking prevalence male\nPrevalence (%) of daily smoking for men,Smoking prevalence female\nPrevalence (%) of daily smoking for women,"Cancers attributable to infections\nProportion of cancers attributable to infections (%), by country","Obesity prevalence male\nInternational variation in the prevalence of obesity, 2016","Obesity prevalence female\nInternational variation in the prevalence of obesity, 2016","Lung cancer incidence rates, male\nAge-standardized rate (world) per 100,000, all ages, 2018","Lung cancer incidence rates, female\nAge-standardized rate (world) per 100,000, all ages, 2018","Cancer survivors\nEstimated number of cancer survivors diagnosed within the past five years per 100,000 population, both sexes, 2018"
0,Afghanistan,0.5,21.4,7,16,3.2,7.6,9.4,3.2,151
1,Algeria,1.1,17.5,2.2,12.9,19.9,34.9,17.4,2.9,312.6
2,Azerbaijan,3.2,36.7,0.3,15.4,15.8,23.6,25.5,2.6,228.1
3,Albania,4.9,40.9,6.1,13.4,21.6,21.8,37.8,7.1,401.1
4,Armenia,5,43.5,1.5,12.2,17.1,23,58.5,8.5,402.2
...,...,...,...,...,...,...,...,...,...,...
202,Réunion,No data,No data,No data,12.4,No data,No data,34.6,9.6,590.1
203,French Polynesia,No data,No data,No data,6.6,No data,No data,55.7,23.4,661.9
204,Guadeloupe,No data,No data,No data,10.2,No data,No data,13,6.5,776.5
205,Guam,No data,No data,No data,8.5,No data,No data,53.7,24.3,418
206,Martinique,No data,No data,No data,6.6,No data,No data,12.3,9.2,747